-- 코드를 작성해주세요
WITH T AS (
    SELECT COUNT(*) AS PARENT_COUNT, PARENT_ID
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT ID, IFNULL(T.PARENT_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN T ON ED.ID = T.PARENT_ID
ORDER BY ID ASC