-- 코드를 작성해주세요
WITH G AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_GROUP
    FROM ECOLI_DATA
),
N AS (
    SELECT ID,
        CASE
            WHEN SIZE_GROUP = 1 THEN 'CRITICAL'
            WHEN SIZE_GROUP = 2 THEN 'HIGH'
            WHEN SIZE_GROUP = 3 THEN 'MEDIUM'
            WHEN SIZE_GROUP = 4 THEN 'LOW'
        END AS COLONY_NAME
    FROM G
)

SELECT G.ID, N.COLONY_NAME
FROM G
JOIN N ON G.ID = N.ID
ORDER BY G.ID