-- 코드를 작성해주세요
WITH RECURSIVE T AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
UNION ALL
    SELECT ED.ID, ED.PARENT_ID, 1+T.GENERATION AS GENERATION
    FROM ECOLI_DATA ED
    JOIN T ON T.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM T
WHERE NOT EXISTS (
    SELECT *
    FROM T T1
    WHERE T.ID = T1.PARENT_ID
)
GROUP BY GENERATION