-- 코드를 작성해주세요
WITH A AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'PYTHON'
),
B AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#'
)


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT CODE FROM A)) = (SELECT CODE FROM A) OR (SKILL_CODE & (SELECT CODE FROM B)) = (SELECT CODE FROM B)
ORDER BY ID ASC