-- 코드를 작성해주세요
WITH A AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'PYTHON'
),
B AS (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#'
)


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT * FROM A) = (SELECT * FROM A)
OR SKILL_CODE & (SELECT * FROM B) = (SELECT * FROM B)
ORDER BY ID ASC