-- 코드를 작성해주세요
WITH T1 AS (
    SELECT MAX(SIZE_OF_COLONY) AS BEST, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (T.BEST - A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM T1 T
JOIN ECOLI_DATA A ON T.YEAR = YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR(A.DIFFERENTIATION_DATE) ASC, (T.BEST - A.SIZE_OF_COLONY) ASC