-- 코드를 작성해주세요
WITH T AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FI.ID AS ID, FN.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
JOIN T ON FI.FISH_TYPE = T.FISH_TYPE
WHERE FI.FISH_TYPE = T.FISH_TYPE AND FI.LENGTH = T.LENGTH
ORDER BY FI.ID ASC
